# Generated by Django 5.1.3 on 2025-01-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='created_by_google_auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_created_by_google_auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_created_by_user', to='rajneehsoulapiapp.emailidregistration'),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='28-01-2025 11:07:02 PM', max_length=200),
        ),
    ]
