# Generated by Django 5.1.3 on 2024-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomnavoption',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='09-12-2024 06:49:33 AM', max_length=200),
        ),
    ]
