# Generated by Django 5.1.3 on 2025-01-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboratordetail',
            old_name='group_expense_id',
            new_name='group_id',
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='19-01-2025 09:46:34 PM', max_length=200),
        ),
    ]
