# Generated by Django 5.1.3 on 2025-01-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0002_alter_scheduleitemlist_lastscheduleon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexpense',
            name='requested_payment_url',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='settle_medium',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='settle_mode',
        ),
        migrations.AddField(
            model_name='collaboratordetail',
            name='redirect_upi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratordetail',
            name='requested_payment_qr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboratordetail',
            name='settle_medium',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collaboratordetail',
            name='settle_mode',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='05-01-2025 08:42:28 AM', max_length=200),
        ),
        migrations.DeleteModel(
            name='CollaboratorPaymentRequest',
        ),
    ]
