# Generated by Django 5.1.3 on 2025-02-17 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0002_otpconfig_alter_authtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 0, 36, 29, 813283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpconfig',
            name='config_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='17-02-2025 06:04:29 AM', max_length=200),
        ),
    ]
