# Generated by Django 5.1.3 on 2025-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0002_expenseitem_created_by_google_auth_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexpense',
            name='t_amt',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='t_item',
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='i_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='01-02-2025 06:41:37 PM', max_length=200),
        ),
    ]
