# Generated by Django 5.1.3 on 2025-02-17 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0003_alter_authtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpconfig',
            old_name='config_value',
            new_name='via_mail',
        ),
        migrations.RemoveField(
            model_name='otpconfig',
            name='config_key',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 0, 41, 28, 799780, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='17-02-2025 06:09:28 AM', max_length=200),
        ),
    ]
