# Generated by Django 5.1.3 on 2025-01-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0003_remove_groupexpense_requested_payment_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboratordetail',
            old_name='group_expense',
            new_name='group_expense_id',
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='05-01-2025 10:08:09 AM', max_length=200),
        ),
    ]
