# Generated by Django 5.1.3 on 2025-02-01 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0003_remove_groupexpense_t_amt_remove_groupexpense_t_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 13, 56, 48, 904288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='01-02-2025 07:24:48 PM', max_length=200),
        ),
    ]
