# Generated by Django 5.1.3 on 2025-02-17 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0004_rename_config_value_otpconfig_via_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 0, 41, 35, 536084, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='17-02-2025 06:09:35 AM', max_length=200),
        ),
    ]
