# Generated by Django 5.1.3 on 2025-04-06 07:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0006_collaboratordetail_collaborator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitemlist',
            name='attachedImage',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 7, 32, 49, 672545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='06-04-2025 01:00:49 PM', max_length=200),
        ),
        migrations.CreateModel(
            name='ScheduleListAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='schedule_list/attachments/files/')),
                ('base_url', models.URLField(default='https://smartelistapi.pythonanywhere.com')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rajneehsoulapiapp.scheduleitemlist')),
            ],
        ),
    ]
