# Generated by Django 5.1.3 on 2025-04-06 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0007_remove_scheduleitemlist_attachedimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelistattachments',
            name='base_url',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 8, 48, 36, 426340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='06-04-2025 02:16:36 PM', max_length=200),
        ),
    ]
