# Generated by Django 5.1.3 on 2025-04-06 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajneehsoulapiapp', '0008_remove_schedulelistattachments_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 9, 44, 18, 236839, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='06-04-2025 03:12:18 PM', max_length=200),
        ),
    ]
